version: "3"

services:
  # app:
  #   restart: always
  #   build: .
  #   ports:
  #     - "6700:6700"
  postgresql:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: fastack_user
      POSTGRES_PASSWORD: fastack_password
      POSTGRES_DB: celery_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    ports:
      - 5888:5432
  redis:
    image: redis:alpine
    restart: always
    ports:
    -   6900:6379
    volumes:
    -   redis-data:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_VHOST=celery_vhost
      - RABBITMQ_DEFAULT_USER=strong_user
      - RABBITMQ_DEFAULT_PASS=strong_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  postgresql-data:
  redis-data:
  rabbitmq_data:
