"""empty message

Revision ID: 9aa2aebe5d0c
Revises:
Create Date: 2022-01-20 20:05:47.528817

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9aa2aebe5d0c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "counter",
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "counter", sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("counter", "state")
    op.drop_column("counter", "task_id")
    # ### end Alembic commands ###
